title: Samurai blog
author: Oleksandr Kulinich
url: ''
description: >
  This is very basic variant of my blog.
permalink: '/:slug.html'
favicon: ./logo.png
remote_theme: abhinavs/moonwalk
theme_config:
  appearance: dark
  back_home_text: home..
  date_format: '%Y-%m-%d'
  show_description: true
  show_navbar: true
  show_footer: true
  show_projects: true
  show_old_projects: true
  show_misc_list: true
sass:
  style: ':compressed'
plugins:
  - jekyll-feed
  - jekyll-seo-tag
baseurl: ''
